### ISSUE TITLE
No devices exposed to ha

### ISSUE THREAD

**Issue by en2te** [lociii/homeassistant-digitalstrom#2]
Me again. I updated homeassistant and all devices disappeared from ha. Deinstalled everything and installed your latest version but they don't come back. The integration installs successfully but no devices. Any idea what i can try?

**Comment by lociii** [comment]
Can you please post your startup log?
Running fine for me on 0.104

**Comment by en2te** [comment]
The day after i posted the issue everything showed up again after it did not for weeks but this morning everything was gone again. All devices were shown as unavailable in the integration-page. HA is the latest version and your integration as well. A few minutes ago i restarted again and now everything is back and working. Sometimes after restart the devices are there, sometimes not. 

```
Tue Jan 28 2020 08:18:05 GMT+0100 (CET)

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 985, in create_connection
    ssl_handshake_timeout=ssl_handshake_timeout)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1013, in _create_connection_transport
    await waiter
ConnectionAbortedError: SSL handshake is taking longer than 60.0 seconds: aborting the connection

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pydigitalstrom/requesthandler.py", line 29, in raw_request
    async with session.get(url=url, **kwargs) as response:
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 483, in _request
    timeout=real_timeout
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 859, in _create_connection
    req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 1004, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 986, in _create_direct_connection
    req=req, client_error=client_error)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 943, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.178.189:8080 ssl:None [None]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/digitalstrom/__init__.py", line 91, in digitalstrom_discover_devices
    await client.initialize()
  File "/usr/local/lib/python3.7/site-packages/pydigitalstrom/client.py", line 77, in initialize
    response = await self.request(url=self.URL_SCENES)
  File "/usr/local/lib/python3.7/site-packages/pydigitalstrom/client.py", line 61, in request
    url=url, params=dict(token=self._session_token), **kwargs
  File "/usr/local/lib/python3.7/site-packages/pydigitalstrom/requesthandler.py", line 42, in raw_request
    raise DSRequestException("request failed")
pydigitalstrom.exceptions.DSRequestException: request failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/digitalstrom/__init__.py", line 94, in digitalstrom_discover_devices
    "Failed to initialize digitalSTROM server at %s", client.host
homeassistant.exceptions.ConfigEntryNotReady: ('Failed to initialize digitalSTROM server at %s', '192.168.178.189')
```

**Comment by lociii** [comment]
OK, same old issue then.
Tried some things on the weekend by using async_get_clientsession from homeassistant.helpers.aiohttp_client and passing it to the library but it all ends in the same issue.
I have no idea why this happens and how to get rid of it. 
Most interesting: it only happens in hass context. Using the pydigitalstrom lib standalone never showed that issue.

Just aked in hass discord - maybe someone has a clue.

**Comment by lociii** [comment]
Unfortunately no one seems to really care on Discord. For now my questions have been answered with meaningless advice. Will keep pushing.

**Comment by lociii** [comment]
On all my tests, the ds server only rejected the first connection attempt.
I've just drafted https://github.com/lociii/homeassistant-digitalstrom/releases/tag/2.3.0 which takes care of that and adds some other improvements. No connection error yet on my local system.
Looking forward to get feedback from you!

**Comment by en2te** [comment]
Seems to work. I did some restarts and never lost connection again. Nice! Thanks again..
